### ISSUE TITLE
Failed AJAX Request Message

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/openpublishing#60] opened 2023-03-08 14:56 UTC
## Description

This is happening in production, not staging.

Users are experiencing a failure message when attempting to publish issues. The user selected cancel from the last publish issue dialog and went back and click "Publish Issue" again. An error message then pops up. (See images below.)

## Image shows user attempting to publish
![image (9)](https://user-images.githubusercontent.com/50670293/223746316-f55a1156-560d-46a2-bd3a-d6c62ea68293.png)

## Image shows error message
![image (10)](https://user-images.githubusercontent.com/50670293/223746506-cc5bbb38-1320-4ce6-95f4-176b600eb82b.png)

## Acceptance Criteria
- [ ] The user should be able to select "ok" to publish the issue and this action should publish as expected.

**Comment by kelynch** [comment] 2023-04-27 18:27
I have been able to reproduce this by unpublishing and trying to republish issue 17 in production.  The issue is successfully unpublished but triggers a 500 error in the browser, and the issue can be republished successfully, but the articles are not visible in the issue.

Here is the error from Apache:

```log
[Thu Apr 27 18:24:22.427032 2023] [php7:error] [pid 31124] [client 128.112.203.144:39742] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P10]: Invalid column reference: 7 ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification in /var/www/ojs-3.3.0-8/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115\n
Stack trace:\n
#0 /var/www/ojs-3.3.0-8/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute()\n
#1 /var/www/ojs-3.3.0-8/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(489): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n
#2 /var/www/ojs-3.3.0-8/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()\n
#3 /var/www/ojs-3.3.0-8/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()\n
#4 /var/www/ojs-3.3.0-8/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(496): Illuminate\\Database\\Connection->run() in /var/www/ojs-3.3.0-8/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671, referer: https://openpublishing.princeton.edu/index.php/pjpf/manageIssues
```

**Comment by kelynch** [comment] 2023-04-27 18:57
This appears to be the same or a similar issue - https://forum.pkp.sfu.ca/t/invalid-column-reference-7-error-there-is-no-unique-or-exclusion-constraint-matching-the-on-conflict-specification/70199

**Comment by kelynch** [comment] 2023-04-27 19:10
Applying [this patch](https://github.com/pkp/ojs/commit/a376551cc031d9fb55f56e20e7de2240bb268cdc#diff-3eeee96f737c976403c06aea886c4c5ceabbfd87714a7dea41836e6c6659c241) manually addressed the issue in production.  I was able to successfully unpublish/publish Issue 17 and 16 (both of which would not publish before) and unpublish/republish issue 27 (which was functioning normally already). 

It appears this code has been updated in OJS 3.3.0-14; we are currently running OJS 3.3.0-8 in staging and production.  I will next attempt to recreate this issue in OJS 3.3.0-8 on staging and apply a fix to the playbook in princeton_ansible, then test on staging.

**Comment by kelynch** [comment] 2023-05-03 21:00
The above-described AJAX issue appears to be inconsistently occurring across browsers, and is not the root cause of the issue of not being able to see submissions in a published issue.  While upgrading to OJS 3.3.0-14 simplifies the workflow, this issue is resolvable within the current UI.

Issues 16, 17, 18, and 19 were fixed (and confirmed as fixed with Yuan and Hannah over Slack) through the following method.

Each submission that is linked to a published issue must be published in production.  Submissions can be unpublished after an issue has been published, and would therefore disappear from the public UI.  If submissions are not appearing in a published issue, this can be fixed as follows:

## Step 1 

Go to the "Submissions" section and locate the submission that is not displaying.  These are searchable under "All Active" or "Archives," depending on the state of the submission.  If the submission's state is anything other than "Published," it will not display publicly in the issue table of contents.

## Step 2

Once you have located the submission, click the "View" button.

<img width="1558" alt="step1" src="https://user-images.githubusercontent.com/7795797/236047060-a3232dae-5627-466a-8b6f-903a6cd61161.png">

## Step 3 

From the "Workflow > Production" tab, click on the "Schedule for Publication" button.

<img width="1550" alt="step2" src="https://user-images.githubusercontent.com/7795797/236047433-92fd4f6e-df7a-406c-a62f-0ca7baafe8c6.png">

## Step 4 

You will be forwarded to the "Workflow > Publication" tab for the submission.  Click the "Schedule for Publication" button here as well.

<img width="1550" alt="step3" src="https://user-images.githubusercontent.com/7795797/236047577-4b62628b-45eb-43bc-8755-70316baaecd2.png">

## Step 5

If everything is correctly set within the submission, you will receive a confirmation dialog box like the following:

<img width="1550" alt="step3 5" src="https://user-images.githubusercontent.com/7795797/236047744-1992c376-21f0-4371-a2b9-1c9c8f58a7be.png">

Click "Publish" to complete publishing the submission.

## Step 6

Once a submission is published, you will see the red band warning that the submission is published and cannot be edited:

<img width="1550" alt="step4" src="https://user-images.githubusercontent.com/7795797/236048004-d5442a2b-4ac3-4cb3-ac9b-f840e5e58860.png">

If you need to edit a submission that has been published, you will need to unpublish it first, then re-publish it when you are done.

## Step 7

To validate that your submission should be visible in the public UI, you can look it up in the "Submissions > Archives" section.  If your submission is present in the search results and has the solid green "Published" label as shown below, your submission should be correctly configured to display in the public UI:

<img width="1466" alt="step5" src="https://user-images.githubusercontent.com/7795797/236048201-81523323-1fa9-4be7-a1ea-871ad75b1bdc.png">

**Comment by kelynch** [comment] 2023-05-03 21:00
I will share the above tutorial with Hannah and Yuan.  Any additional actions needed should be taken on a new ticket.

**Closed as completed by kelynch** 2023-05-03 21:00 UTC
Labels: bug
